---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whoogle
  namespace: flux-system
spec:
  chart:
    spec:
      chart: whoogle
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
  interval: 1m0s
