---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whoogle
  namespace: flux-system
spec:
  chart:
    spec:
      chart: whoogle
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
  interval: 1m0s
  install:
    createNamespace: true
  ingress:
    main:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - host: "w.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "w.${SECRET_DOMAIN}"
          secretName: "whoogle-tls"
