---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nextcloud-charts
  namespace: flux-system
spec:
  interval: 15m0s
  url: https://nextcloud.github.io/helm/
  timeout: 3m
