---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm/
      chart: nextcloud
      version: 2.14.2
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nextcloud
      tag: "24.0.0"

    env:
      PHP_MEMORY_LIMIT: 256M
      NEXTCLOUD_DOMAIN_NAME: cloud.${SECRET_DOMAIN}
    podSecurityContext:
      supplementalGroups:
        - 1001
    persistence:
      enabled: true
      existingClaim: nextcloud-config
      nextcloudData:
        enabled: true
        existingClaim: media-nfs-nextcloud-pvc

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        hajimari.io/icon: "cloud-upload"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: media-nextcloud-dav-redirect@kubernetescrd,media-hsts@kubernetescrd
      tls:
        - secretName: tls.nextcloud
          hosts:
            - cloud.${SECRET_DOMAIN}

    nextcloud:
      host: cloud.${SECRET_DOMAIN}
      username: ${SECRET_NEXTCLOUD_ADMIN_USER}
      password: ${SECRET_NEXTCLOUD_ADMIN_PASSWORD}

      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array('${METALLB_TRAEFIK_ADDR}')
          );
        protocol.config.php: |-
          <?php
          $CONFIG = array (
            'overwriteprotocol' => 'https'
          );
        phone_region.config.php: |-
          <?php
          $CONFIG = array (
            'default_phone_region' => 'US'
          );
      # mail:
      #   enabled: true
      #   fromAddress: cloud
      #   domain: ${SECRET_DOMAIN}
      #   smtp:
      #     host: smtp.mailgun.org
      #     secure: ssl
      #     port: 465
      #     name: ${SECRET_MAILGUN_USERNAME}
      #     password: ${SECRET_MAILGUN_PASSWORD}
    cronjob:
      enabled: true

    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-postgresql.media
      user: nextcloud
      password: ${SECRET_NEXTCLOUD_POSTGRES_PASSWORD}
      database: nextcloud

    postgresql:
      enabled: true

      postgresqlUsername: nextcloud
      postgresqlPassword: ${SECRET_NEXTCLOUD_POSTGRES_PASSWORD}
      postgresqlDatabase: nextcloud

      persistence:
        enabled: true
        existingClaim: nextcloud-postgresql
