---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-nextcloud-pv
  namespace: media
spec:
  storageClassName: media-nfs-nextcloud
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "${NAS_ADDR}"
    path: "/mnt/zp0/nextcloud"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs-nextcloud-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-nfs-nextcloud
  resources:
    requests:
      storage: 1Mi
