---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: libreddit
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: libreddit
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: spikecodes/libreddit
      tag: v0.21.7
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "reddit"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "reddit.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "reddit.${SECRET_DOMAIN}"
            secretName: "libreddit-tls"

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
