---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 1
      defaultFsType: ext4
    defaultSettings:
      backupTarget: ${NAS_BACKUP}
      defaultReplicaCount: 1
      defaultLonghornStaticStorageClass: longhorn
      replicaAutoBalance: best-effort
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "search-web"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "longhorn.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "longhorn.${SECRET_DOMAIN}"
            secretName: "longhorn-tls"
