---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cert-manager
  - kube-vip
  - kured
  - metrics-server
  - reflector
  - reloader
  - node-feature-discovery
  - intel-gpu-plugin
  # - goldilocks
  - kured
