---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-redis-pvc
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
