---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: traefik
      namespace: networking
  values:
    image:
      repository: goauthentik.io/server
      tag: 2022.2.1
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "account-check"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: "auth.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "auth.${SECRET_DOMAIN}"
            secretName: authentik-cert
    authentik:
      log_level: debug
      postgresql:
        name: "postgres"
        user: "postgres"
      secret_key: ${SECRET_AUTHENTIK_KEY}

    postgresql:
      enabled: true
      persistence:
        enabled: true
        existingClaim: authentik-postgresql-pvc

      postgresqlUsername: authentik
      postgresqlDatabase: authentik
      postgresqlPassword: ${SECRET_AUTHENTIK_POSTGRES_PASSWORD}

      resources:
        requests:
          cpu: 15m
          memory: 105M
        limits:
          cpu: 100m
          memory: 200M

    redis:
      enabled: true
      image:
        repository: library/redis
        tag: "6.2.6"

    resources:
      server:
        requests:
          cpu: 15m
          memory: 105M
        limits:
          cpu: 387m
          memory: 611M
      worker:
        requests:
          cpu: 15m
          memory: 105M
        limits:
          cpu: 183m
          memory: 606M
