---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  releaseName: esphome
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: esphome
      version: 8.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 10m
  values:
    image:
      repository: ghcr.io/esphome/esphome
      tag: 2022.5.0
    env:
      TZ: ${TIMEZONE}
      ESPHOME_DASHBOARD_USE_PING: true
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918-ips@kubernetescrd"
          hajimari.io/enable: "true"
          hajimari.io/icon: "car-esp"
        hosts:
          - host: "esphome.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "esphome.${SECRET_DOMAIN}"
            secretName: "esphome-cert"
    persistence:
      config:
        enabled: true
        existingClaim: esphome-config-pvc
