# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:qBQMBJOOEswWKRUnLA9L+FqehO3zFgR4UIoifcnxyQqPGcwgIQ==,iv:q2bVT7h0TcMn+rTWq9DEjkWWvcGeiXFopaw6d7C6GGo=,tag:6HJdqnpXyJuUcgrMKzBy+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17xng9nl2lcy5arx8rkq4al8ffn4dgtl3k5ra80cuk0u36ffrj4zsm7cwy0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwK01EN1gyd1pWU2paay8x
            RGZoZEY2RGsweHZ1cUhUTGF5MDF2SlpCTG1vCjdCQVBaRFZ2dnpQb3NYaE5OMjNH
            cnZpYlNiZlBXT1Y3V0d5dzJtVzNLRGsKLS0tIFhtWkhkRDJqVlVOTWxoTUpXaHk2
            SndHaGorSlJOZlAxTUhSV1ZRRU1IS2sKNqB7vV9WIaUkSaCDTUL8kbzGBsy5YtRt
            Ppvqo9dCz8C7xspyL3ojdKOuO3et9SERtaW06gFY6BRZfl2EDvjQiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-09T10:52:17Z"
    mac: ENC[AES256_GCM,data:EW/XjRqkrabLLA/Ca5GUYJhzoKCoFAyqHIQ4w46Kir0dXm+92aieMHKEZ6GXeAvGSG+WUsQ34497dzcKpctRn4WEpR7MowDijw78aJadeHpDcqXRHgT8c4RiizHpeDY0ay0NM5GRpMF6ZxNdc+ErOrtBXgSwYp9hruCoOyWiiRU=,iv:b45l9ThbgjmQfIs5GQxNSlvITDpNZR4wdsrKXv57wHY=,tag:KU5GyBkT84x4KxaHf6aiOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
