---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: error-pages
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: k8s-gitops
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: traefik
      namespace: network
  values:
    image:
      repository: ghcr.io/tarampampam/error-pages
      tag: 2.7.0
    controller:
      enabled: true
      type: deployment
      strategy: RollingUpdate
      replicas: 1
    nameOverride: error-pages
    env:
      TEMPLATE_NAME: lost-in-space
    service:
      main:
        ports:
          http:
            port: 8080
    resources:
      requests:
        cpu: 15m
        memory: 105M
      limits:
        cpu: 50m
        memory: 305M
