---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: node-problem-detector
      version: 2.0.9
      sourceRef:
        kind: HelmRepository
        name: deliveryhero-charts
        namespace: flux-system
      interval: 10m
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
