kind: Secret
ansible_user: ENC[AES256_GCM,data:cX56,iv:9AsrJd8+b5nbN2pPXd+YFBw4v52If40K6+ogJEO71mo=,tag:hYFrmfGBkDEdXlBXHoZ3lQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:G5S0BdDCAgPTvA==,iv:gRrg7dIFPy14i0iQMOsG7H+w5l8MBbgHSIsDTvRqvQM=,tag:qhGlKRFHCPSeCNhVC9zUAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17xng9nl2lcy5arx8rkq4al8ffn4dgtl3k5ra80cuk0u36ffrj4zsm7cwy0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWUwwZ0pFU3JoMzY0Q2Vh
            ZFhEdCtTM2dhQzZWS1k1NUdhL0ZkTnBJa2tZClExS21LMmZLTUZ4TFN1NzI1bktt
            TlRWdmtGMlNScnEra0l6cG9TZXhTSTAKLS0tIEh2T2xsb2dEK1RTYmdUbzN4eHM1
            TWJBUlFXWVN4NGo5QUV6dU14M1c0TVEKybBxfsFphJ7wP5Iy0QGVOK4aAbjmkowS
            k/hOIP3nMfIXIEbA6/bMpT9uI9Pp1cOstAAMLePB2CdXHekcPeQmrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-24T16:13:57Z"
    mac: ENC[AES256_GCM,data:DergnjRpdoh8eD93gFbI/0OdgVWz2KIzfT+ez5mNlo7xYtyQiI673WUId6zddt38SMFIYzf2/N2PiVQD65Htcs2LIj1RnqbvoNmn+Ak/Rvg0uYfdgCPyHYPThEjYZcX3HA5LWWPZkDPt5V8aYLxBNW0BXuPB1vNXV6XQJ46BqAw=,iv:hBnc6rZmm40u4Mu8Ggsqo/ETHvvE2iO1KIHW9PpZP74=,tag:dQB3yoWn7B0a2hd9BUAWlg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
