---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Stockholm"
  METALLB_LB_RANGE: 10.0.10.20-10.0.10.30
  METALLB_TRAEFIK_ADDR: 10.0.10.20
  NAS_ADDR: 10.0.10.10
