---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarr
      version: 16.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr-develop
      tag: v3.0.6.1457
    podSecurityContext:
      supplementalGroups:
        - 1000
    env:
      TZ: "Europe/Stockholm"
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      media:
        enabled: true
        existingClaim: media-nfs-media-pvc
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "sonarr.${SECRET_DOMAIN}"
            secretName: sonarr-cert
    resources:
      requests:
        cpu: "0.04"
        memory: "256M"
      limits:
        memory: "512M"
