---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ombi
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: ombi
      version: 11.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: traefik
      namespace: networking
  values:
    env:
      TZ: "${TIMEZONE}"
      PUID: "1000"
      GUID: "1000"
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: ombi-config
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "movie-search"
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: "ombi.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "ombi.${SECRET_DOMAIN}"
            secretName: ombi-cert
      resources:
        requests:
          cpu: 15m
          memory: 105M
        limits:
          cpu: 256m
          memory: 129M
