---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: authentik
  namespace: networking
spec:
  forwardAuth:
    address: https://auth.${SECRET_DOMAIN}/outpost.goauthentik.io/auth/traefik
    trustForwardHeader: true
    authResponseHeadersRegex: ^.*$
