---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app unpackerr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/onedr0p/unpackerr
      tag: 0.10.1@sha256:8f5ec05e0ef4102b4f6340e4adeffa59d521a173530a6effffc59ac1c6e49d97
    env:
      TZ: ${TIMEZONE}
      UN_SONARR_0_URL: http://sonarr
      UN_SONARR_0_PATHS_0: /complete/downloads
      UN_RADARR_0_URL: http://radarr
      UN_RADARR_0_PATHS_0: /complete/downloads
    envFrom:
      - secretRef:
          name: unpackerr
    persistence:
      config:
        enabled: false
      complete:
        enabled: true
        existingClaim: media-nfs-media-pvc
        mountPath: /complete
