---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app unpackerr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/docs/
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/onedr0p/unpackerr
      tag: 0.10.1@sha256:758cb8e96e9972ecedbfb5c136dc5c75dd0cf0d7ae6131867f0d27611773e86c
    env:
      TZ: ${TIMEZONE}
      UN_SONARR_0_URL: http://sonarr
      UN_SONARR_0_PATHS_0: /complete/downloads
      UN_RADARR_0_URL: http://radarr
      UN_RADARR_0_PATHS_0: /complete/downloads
    envFrom:
      - secretRef:
          name: unpackerr
    persistence:
      config:
        enabled: false
      complete:
        enabled: true
        existingClaim: media-nfs-media-pvc
        mountPath: /complete
