---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - jellyfin
  - media-pvc
  - qbittorrent
  - sonarr
  - radarr
  - prowlarr
  - bazarr
  - unpackerr
